CREATE TABLE objects (
    id INT UNSIGNED,
    name VARCHAR(255) COLLATE latin1_general_cs,
    display_name VARCHAR(255) COLLATE latin1_general_cs,
    alias VARCHAR(255) COLLATE latin1_general_cs,
    address VARCHAR(255) COLLATE latin1_general_cs,
    check_command VARCHAR(255) COLLATE latin1_general_cs,
    initial_state INT,
    check_interval DECIMAL,
    retry_interval DECIMAL,
    max_attempts INT,
    event_handler VARCHAR(255) COLLATE latin1_general_cs,
    notification_interval DECIMAL,
    first_notification_delay DECIMAL,
    notification_options INT UNSIGNED,
    hourly_value INT UNSIGNED,
    notification_period VARCHAR(255) COLLATE latin1_general_cs,
    check_period VARCHAR(255) COLLATE latin1_general_cs,
    flap_detection_enabled INT,
    low_flap_threshold DECIMAL,
    high_flap_threshold DECIMAL,
    flap_detection_options INT,
    stalking_options INT UNSIGNED,
    check_freshness INT,
    freshness_threshold INT,
    process_performance_data INT,
    checks_enabled INT,
    check_source VARCHAR(255) COLLATE latin1_general_cs,
    accept_passive_checks INT,
    event_handler_enabled INT,
    retain_status_information INT,
    retain_nonstatus_information INT,
    obsess INT,
    notes VARCHAR(255) COLLATE latin1_general_cs,
    notes_url VARCHAR(255) COLLATE latin1_general_cs,
    action_url VARCHAR(255) COLLATE latin1_general_cs,
    icon_image VARCHAR(255) COLLATE latin1_general_cs,
    icon_image_alt VARCHAR(255) COLLATE latin1_general_cs,
    statusmap_image VARCHAR(255) COLLATE latin1_general_cs,
    vrml_image VARCHAR(255) COLLATE latin1_general_cs,
    have_2d_coords INT,
    x_2d INT,
    y_2d INT,
    have_3d_coords INT,
    x_3d DECIMAL,
    y_3d DECIMAL,
    z_3d DECIMAL,
    problem_has_been_acknowledged INT,
    acknowledgement_type INT,
    check_type INT,
    current_state INT,
    last_state INT,
    last_hard_state INT,
    plugin_output VARCHAR(255) COLLATE latin1_general_cs,
    long_plugin_output VARCHAR(255) COLLATE latin1_general_cs,
    perf_data VARCHAR(255) COLLATE latin1_general_cs,
    state_type INT,
    current_attempt INT,
    current_event_id BIGINT UNSIGNED,
    last_event_id BIGINT UNSIGNED,
    current_problem_id BIGINT UNSIGNED,
    last_problem_id BIGINT UNSIGNED,
    latency DECIMAL,
    execution_time DECIMAL,
    is_executing INT,
    check_options INT,
    notifications_enabled INT,
    last_notification TIMESTAMP,
    next_notification TIMESTAMP,
    next_check TIMESTAMP,
    last_check TIMESTAMP,
    last_state_change TIMESTAMP,
    last_hard_state_change TIMESTAMP,
    last_time_up TIMESTAMP,
    last_time_down TIMESTAMP,
    last_time_unreachable TIMESTAMP,
    has_been_checked INT,
    is_being_freshened INT,
    notified_on INT,
    current_notification_number INT,
    no_more_notifications INT,
    current_notification_id BIGINT UNSIGNED,
    check_flapping_recovery_notification INT,
    scheduled_downtime_depth INT,
    pending_flex_downtime INT,
    state_history_index INT,
    last_state_history_update TIMESTAMP,
    is_flapping INT,
    flapping_comment_id BIGINT UNSIGNED,
    percent_state_change DECIMAL,
    total_services INT,
    modified_attributes BIGINT UNSIGNED
) ENGINE=MEMORY;

CREATE TABLE services (
    event_handler_args VARCHAR(255) COLLATE latin1_general_cs,
    modified_attributes BIGINT UNSIGNED,
    percent_state_change DECIMAL,
    flapping_comment_id BIGINT UNSIGNED,
    is_flapping INT,
    state_history_index INT,
    pending_flex_downtime INT,
    scheduled_downtime_depth INT,
    check_options INT,
    is_executing INT,
    execution_time DECIMAL,
    latency DECIMAL,
    current_notification_id BIGINT UNSIGNED,
    current_notification_number INT,
    notified_on INT UNSIGNED,
    is_being_freshened INT,
    has_been_checked INT,
    last_time_critical TIMESTAMP,
    last_time_unknown TIMESTAMP,
    last_time_warning TIMESTAMP,
    last_time_ok TIMESTAMP,
    last_hard_state_change TIMESTAMP,
    last_state_change TIMESTAMP,
    check_flapping_recovery_notification INT,
    no_more_notifications INT,
    next_notification TIMESTAMP,
    last_notification TIMESTAMP,
    last_problem_id BIGINT UNSIGNED,
    current_problem_id BIGINT UNSIGNED,
    last_event_id BIGINT UNSIGNED,
    current_event_id BIGINT UNSIGNED,
    current_attempt INT,
    last_check TIMESTAMP,
    next_check TIMESTAMP,
    state_type INT,
    perf_data VARCHAR(255) COLLATE latin1_general_cs,
    long_plugin_output VARCHAR(255) COLLATE latin1_general_cs,
    plugin_output VARCHAR(255) COLLATE latin1_general_cs,
    last_hard_state INT,
    last_state INT,
    current_state INT,
    check_type INT,
    host_problem_at_last_check INT,
    acknowledgement_type INT,
    problem_has_been_acknowledged INT,
    icon_image_alt VARCHAR(255) COLLATE latin1_general_cs,
    icon_image VARCHAR(255) COLLATE latin1_general_cs,
    action_url VARCHAR(255) COLLATE latin1_general_cs,
    notes_url VARCHAR(255) COLLATE latin1_general_cs,
    notes VARCHAR(255) COLLATE latin1_general_cs,
    obsess INT,
    notifications_enabled INT,
    retain_nonstatus_information INT,
    retain_status_information INT,
    check_source VARCHAR(255) COLLATE latin1_general_cs,
    checks_enabled INT,
    event_handler_enabled INT,
    accept_passive_checks INT,
    freshness_threshold INT,
    check_freshness INT,
    process_performance_data INT,
    flap_detection_options INT UNSIGNED,
    high_flap_threshold DECIMAL,
    low_flap_threshold DECIMAL,
    flap_detection_enabled INT,
    check_period VARCHAR(255) COLLATE latin1_general_cs,
    notification_period VARCHAR(255) COLLATE latin1_general_cs,
    is_volatile INT,
    hourly_value INT UNSIGNED,
    stalking_options INT UNSIGNED,
    notification_options INT UNSIGNED,
    first_notification_delay DECIMAL,
    notification_interval DECIMAL,
    max_attempts INT,
    retry_interval DECIMAL,
    check_interval DECIMAL,
    initial_state INT,
    event_handler VARCHAR(255) COLLATE latin1_general_cs,
    check_command VARCHAR(255) COLLATE latin1_general_cs,
    display_name VARCHAR(255) COLLATE latin1_general_cs,
    description VARCHAR(255) COLLATE latin1_general_cs,
    host_name VARCHAR(255) COLLATE latin1_general_cs,
    id INT UNSIGNED
) ENGINE=MEMORY;